spring:
  datasource:
    platform: h2
    url: jdbc:h2:~/apps/h2db/apidemo;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: local


server:
  port: 80

jwt:
  secretKey: secret
  validateMills: 864000000